name: Deploy WordPress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to AWS EC2
        env:
          SSH_KEY: ${{ secrets.SHA256:Maq/HKXzWiYLmQPbQO+TCP2Cd6FatQ2g38dKvbuhJI0
 }}
          SERVER_IP: ${{ secrets.35.169.159.103 }}
          USER: ubuntu
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem
          rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" ./ ubuntu@$SERVER_IP:/var/www/html/
          ssh -i key.pem -o StrictHostKeyChecking=no ubuntu@$SERVER_IP "sudo systemctl restart nginx php8.1-fpm"
